//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using Njh.Kernel.Kentico.Models.PageTypes;

[assembly: RegisterDocumentType(PageType_NavItem.CLASS_NAME, typeof(PageType_NavItem))]

namespace Njh.Kernel.Kentico.Models.PageTypes
{
    /// <summary>
    /// Represents a content item of type PageType_NavItem.
    /// </summary>
    public partial class PageType_NavItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NJH.PageType_NavItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_NavItem fields.
        /// </summary>
        private readonly PageType_NavItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_NavItemID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_NavItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_NavItemID"), 0);
            }
            set
            {
                SetValue("PageType_NavItemID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Display Title.
        /// </summary>
        [DatabaseField]
        public string DisplayTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DisplayTitle"), @"");
            }
            set
            {
                SetValue("DisplayTitle", value);
            }
        }


        /// <summary>
        /// Link Page.
        /// </summary>
        [DatabaseField]
        public Guid LinkPage
        {
            get
            {
                return ValidationHelper.GetGuid(GetValue("LinkPage"), Guid.Empty);
            }
            set
            {
                SetValue("LinkPage", value);
            }
        }

        /// <summary>
        /// Link Type.
        /// </summary>
        [DatabaseField]
        public string CssClass
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CssClass"), @"");
            }
            set
            {
                SetValue("CssClass", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_NavItem fields.
        /// </summary>
        [RegisterProperty]
        public PageType_NavItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_NavItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_NavItemFields : AbstractHierarchicalObject<PageType_NavItemFields>
        {
            /// <summary>
            /// The content item of type PageType_NavItem that is a target of the extended API.
            /// </summary>
            private readonly PageType_NavItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_NavItemFields" /> class with the specified content item of type PageType_NavItem.
            /// </summary>
            /// <param name="instance">The content item of type PageType_NavItem that is a target of the extended API.</param>
            public PageType_NavItemFields(PageType_NavItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_NavItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_NavItemID;
                }
                set
                {
                    mInstance.PageType_NavItemID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Display Title.
            /// </summary>
            public string DisplayTitle
            {
                get
                {
                    return mInstance.DisplayTitle;
                }
                set
                {
                    mInstance.DisplayTitle = value;
                }
            }


            /// <summary>
            /// Link Page.
            /// </summary>
            public Guid LinkPage
            {
                get
                {
                    return mInstance.LinkPage;
                }
                set
                {
                    mInstance.LinkPage = value;
                }
            }

            /// <summary>
            /// Link Type.
            /// </summary>
            public string CssClass
            {
                get
                {
                    return mInstance.CssClass;
                }
                set
                {
                    mInstance.CssClass = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_NavItem" /> class.
        /// </summary>
        public PageType_NavItem() : base(CLASS_NAME)
        {
            mFields = new PageType_NavItemFields(this);
        }

        #endregion
    }
}