//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using Njh.Kernel.Kentico.Models.PageTypes;

[assembly: RegisterDocumentType(PageType_AccordionItem.CLASS_NAME, typeof(PageType_AccordionItem))]

namespace Njh.Kernel.Kentico.Models.PageTypes
{
    /// <summary>
    /// Represents a content item of type PageType_AccordionItem.
    /// </summary>
    public partial class PageType_AccordionItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NJH.PageType_AccordionItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_AccordionItem fields.
        /// </summary>
        private readonly PageType_AccordionItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_AccordionItemID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_AccordionItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_AccordionItemID"), 0);
            }
            set
            {
                SetValue("PageType_AccordionItemID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Content.
        /// </summary>
        [DatabaseField]
        public string Content
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Content"), @"");
            }
            set
            {
                SetValue("Content", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_AccordionItem fields.
        /// </summary>
        [RegisterProperty]
        public PageType_AccordionItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_AccordionItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_AccordionItemFields : AbstractHierarchicalObject<PageType_AccordionItemFields>
        {
            /// <summary>
            /// The content item of type PageType_AccordionItem that is a target of the extended API.
            /// </summary>
            private readonly PageType_AccordionItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_AccordionItemFields" /> class with the specified content item of type PageType_AccordionItem.
            /// </summary>
            /// <param name="instance">The content item of type PageType_AccordionItem that is a target of the extended API.</param>
            public PageType_AccordionItemFields(PageType_AccordionItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_AccordionItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_AccordionItemID;
                }
                set
                {
                    mInstance.PageType_AccordionItemID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Content.
            /// </summary>
            public string Content
            {
                get
                {
                    return mInstance.Content;
                }
                set
                {
                    mInstance.Content = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_AccordionItem" /> class.
        /// </summary>
        public PageType_AccordionItem() : base(CLASS_NAME)
        {
            mFields = new PageType_AccordionItemFields(this);
        }

        #endregion
    }
}