//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using Njh.Kernel.Kentico.Models.PageTypes;

[assembly: RegisterDocumentType(PageType_SliderImage.CLASS_NAME, typeof(PageType_SliderImage))]

namespace Njh.Kernel.Kentico.Models.PageTypes
{
    /// <summary>
    /// Represents a content item of type PageType_SliderImage.
    /// </summary>
    public partial class PageType_SliderImage : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NJH.PageType_SliderImage";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_SliderImage fields.
        /// </summary>
        private readonly PageType_SliderImageFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// SliderImageID.
        /// </summary>
        [DatabaseIDField]
        public int SliderImageID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("SliderImageID"), 0);
            }
            set
            {
                SetValue("SliderImageID", value);
            }
        }


        /// <summary>
        /// Slide title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Slide Image.
        /// </summary>
        [DatabaseField]
        public string SlideImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SlideImage"), @"");
            }
            set
            {
                SetValue("SlideImage", value);
            }
        }


        /// <summary>
        /// Alt Text.
        /// </summary>
        [DatabaseField]
        public string ImageAltText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("ImageAltText"), @"");
            }
            set
            {
                SetValue("ImageAltText", value);
            }
        }


        /// <summary>
        /// Mobile Slide Image.
        /// </summary>
        [DatabaseField]
        public string MobileSlideImage
        {
            get
            {
                return ValidationHelper.GetString(GetValue("MobileSlideImage"), @"");
            }
            set
            {
                SetValue("MobileSlideImage", value);
            }
        }


        /// <summary>
        /// Content / Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Link URL.
        /// </summary>
        [DatabaseField]
        public string LinkUrl
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkUrl"), @"");
            }
            set
            {
                SetValue("LinkUrl", value);
            }
        }


        /// <summary>
        /// Link Title.
        /// </summary>
        [DatabaseField]
        public string LinkTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("LinkTitle"), @"");
            }
            set
            {
                SetValue("LinkTitle", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_SliderImage fields.
        /// </summary>
        [RegisterProperty]
        public PageType_SliderImageFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_SliderImage fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_SliderImageFields : AbstractHierarchicalObject<PageType_SliderImageFields>
        {
            /// <summary>
            /// The content item of type PageType_SliderImage that is a target of the extended API.
            /// </summary>
            private readonly PageType_SliderImage mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_SliderImageFields" /> class with the specified content item of type PageType_SliderImage.
            /// </summary>
            /// <param name="instance">The content item of type PageType_SliderImage that is a target of the extended API.</param>
            public PageType_SliderImageFields(PageType_SliderImage instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// SliderImageID.
            /// </summary>
            public int SliderImageID
            {
                get
                {
                    return mInstance.SliderImageID;
                }
                set
                {
                    mInstance.SliderImageID = value;
                }
            }


            /// <summary>
            /// Slide title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Slide Image.
            /// </summary>
            public string SlideImage
            {
                get
                {
                    return mInstance.SlideImage;
                }
                set
                {
                    mInstance.SlideImage = value;
                }
            }


            /// <summary>
            /// Alt Text.
            /// </summary>
            public string ImageAltText
            {
                get
                {
                    return mInstance.ImageAltText;
                }
                set
                {
                    mInstance.ImageAltText = value;
                }
            }


            /// <summary>
            /// Mobile Slide Image.
            /// </summary>
            public string MobileSlideImage
            {
                get
                {
                    return mInstance.MobileSlideImage;
                }
                set
                {
                    mInstance.MobileSlideImage = value;
                }
            }


            /// <summary>
            /// Content / Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// Link URL.
            /// </summary>
            public string LinkUrl
            {
                get
                {
                    return mInstance.LinkUrl;
                }
                set
                {
                    mInstance.LinkUrl = value;
                }
            }


            /// <summary>
            /// Link Title.
            /// </summary>
            public string LinkTitle
            {
                get
                {
                    return mInstance.LinkTitle;
                }
                set
                {
                    mInstance.LinkTitle = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_SliderImage" /> class.
        /// </summary>
        public PageType_SliderImage() : base(CLASS_NAME)
        {
            mFields = new PageType_SliderImageFields(this);
        }

        #endregion
    }
}