//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using Njh.Kernel.Kentico.Models.PageTypes;

[assembly: RegisterDocumentType(PageType_Alert.CLASS_NAME, typeof(PageType_Alert))]

namespace Njh.Kernel.Kentico.Models.PageTypes
{
    /// <summary>
    /// Represents a content item of type PageType_Alert.
    /// </summary>
    public partial class PageType_Alert : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NJH.PageType_Alert";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_Alert fields.
        /// </summary>
        private readonly PageType_AlertFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// AlertID.
        /// </summary>
        [DatabaseIDField]
        public int AlertID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("AlertID"), 0);
            }
            set
            {
                SetValue("AlertID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_Alert fields.
        /// </summary>
        [RegisterProperty]
        public PageType_AlertFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_Alert fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_AlertFields : AbstractHierarchicalObject<PageType_AlertFields>
        {
            /// <summary>
            /// The content item of type PageType_Alert that is a target of the extended API.
            /// </summary>
            private readonly PageType_Alert mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_AlertFields" /> class with the specified content item of type PageType_Alert.
            /// </summary>
            /// <param name="instance">The content item of type PageType_Alert that is a target of the extended API.</param>
            public PageType_AlertFields(PageType_Alert instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// AlertID.
            /// </summary>
            public int AlertID
            {
                get
                {
                    return mInstance.AlertID;
                }
                set
                {
                    mInstance.AlertID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_Alert" /> class.
        /// </summary>
        public PageType_Alert() : base(CLASS_NAME)
        {
            mFields = new PageType_AlertFields(this);
        }

        #endregion
    }
}