//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using Njh.Kernel.Kentico.Models.PageTypes;

[assembly: RegisterDocumentType(PageType_SocialMediaLink.CLASS_NAME, typeof(PageType_SocialMediaLink))]

namespace Njh.Kernel.Kentico.Models.PageTypes
{
    /// <summary>
    /// Represents a content item of type PageType_SocialMediaLink.
    /// </summary>
    public partial class PageType_SocialMediaLink : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "NJH.PageType_SocialMediaLink";


        /// <summary>
        /// The instance of the class that provides extended API for working with PageType_SocialMediaLink fields.
        /// </summary>
        private readonly PageType_SocialMediaLinkFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// PageType_NavItemID.
        /// </summary>
        [DatabaseIDField]
        public int PageType_SocialMediaLinkID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("PageType_SocialMediaLinkID"), 0);
            }
            set
            {
                SetValue("PageType_SocialMediaLinkID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Display Title.
        /// </summary>
        [DatabaseField]
        public string DisplayTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DisplayTitle"), @"");
            }
            set
            {
                SetValue("DisplayTitle", value);
            }
        }


        /// <summary>
        /// Link Page.
        /// </summary>
        [DatabaseField]
        public string Link
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Link"), @"");
            }
            set
            {
                SetValue("Link", value);
            }
        }


        /// <summary>
        /// Link Type.
        /// </summary>
        [DatabaseField]
        public string CssClass
        {
            get
            {
                return ValidationHelper.GetString(GetValue("CssClass"), @"");
            }
            set
            {
                SetValue("CssClass", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with PageType_SocialMediaLink fields.
        /// </summary>
        [RegisterProperty]
        public PageType_SocialMediaLinkFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with PageType_SocialMediaLink fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class PageType_SocialMediaLinkFields : AbstractHierarchicalObject<PageType_SocialMediaLinkFields>
        {
            /// <summary>
            /// The content item of type PageType_SocialMediaLink that is a target of the extended API.
            /// </summary>
            private readonly PageType_SocialMediaLink mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="PageType_SocialMediaLinkFields" /> class with the specified content item of type PageType_SocialMediaLink.
            /// </summary>
            /// <param name="instance">The content item of type PageType_SocialMediaLink that is a target of the extended API.</param>
            public PageType_SocialMediaLinkFields(PageType_SocialMediaLink instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// PageType_NavItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.PageType_SocialMediaLinkID;
                }
                set
                {
                    mInstance.PageType_SocialMediaLinkID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Display Title.
            /// </summary>
            public string DisplayTitle
            {
                get
                {
                    return mInstance.DisplayTitle;
                }
                set
                {
                    mInstance.DisplayTitle = value;
                }
            }


            /// <summary>
            /// Link Page.
            /// </summary>
            public string Link
            {
                get
                {
                    return mInstance.Link;
                }
                set
                {
                    mInstance.Link = value;
                }
            }


            /// <summary>
            /// Link Type.
            /// </summary>
            public string CssClass
            {
                get
                {
                    return mInstance.CssClass;
                }
                set
                {
                    mInstance.CssClass = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="PageType_SocialMediaLink" /> class.
        /// </summary>
        public PageType_SocialMediaLink() : base(CLASS_NAME)
        {
            mFields = new PageType_SocialMediaLinkFields(this);
        }

        #endregion
    }
}