//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using Njh.Kernel.Kentico.Models.CustomTables;

[assembly: RegisterCustomTable(CustomTable_JobTitleItem.CLASS_NAME, typeof(CustomTable_JobTitleItem))]

namespace Njh.Kernel.Kentico.Models.CustomTables
{
    /// <summary>
    /// Represents a content item of type CustomTable_JobTitleItem.
    /// </summary>
    public partial class CustomTable_JobTitleItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "Njh.CustomTable_JobTitle";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_JobTitleItem fields.
        /// </summary>
        private readonly CustomTable_JobTitleItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// URL.
        /// </summary>
        [DatabaseField]
        public string Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Url"), @"");
            }
            set
            {
                SetValue("Url", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_JobTitleItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_JobTitleItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_JobTitleItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CustomTable_JobTitleItemFields : AbstractHierarchicalObject<CustomTable_JobTitleItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_JobTitleItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_JobTitleItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_JobTitleItemFields" /> class with the specified content item of type CustomTable_JobTitleItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_JobTitleItem that is a target of the extended API.</param>
            public CustomTable_JobTitleItemFields(CustomTable_JobTitleItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// URL.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.Url;
                }
                set
                {
                    mInstance.Url = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_JobTitleItem" /> class.
        /// </summary>
        public CustomTable_JobTitleItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_JobTitleItemFields(this);
        }

        #endregion
    }
}