
//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS;
using CMS.Base;
using CMS.CustomTables;
using CMS.DataEngine;
using CMS.Helpers;
using Njh.Kernel.Kentico.Models.CustomTables;

[assembly: RegisterCustomTable(CustomTable_SectionColorThemesItem.CLASS_NAME, typeof(CustomTable_SectionColorThemesItem))]

namespace Njh.Kernel.Kentico.Models.CustomTables
{
    /// <summary>
    /// Represents a content item of type CustomTable_SectionColorThemesItem.
    /// </summary>
    public partial class CustomTable_SectionColorThemesItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Njh.CustomTable_SectionColorThemes";


		/// <summary>
		/// The instance of the class that provides extended API for working with CustomTable_SectionColorThemesItem fields.
		/// </summary>
		private readonly CustomTable_SectionColorThemesItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Name.
		/// </summary>
		[DatabaseField]
		public string Name
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Name"), @"");
			}
			set
			{
				SetValue("Name", value);
			}
		}


		/// <summary>
		/// Css Class.
		/// </summary>
		[DatabaseField]
		public string CssClass
		{
			get
			{
				return ValidationHelper.GetString(GetValue("CssClass"), @"");
			}
			set
			{
				SetValue("CssClass", value);
			}
		}


		/// <summary>
		/// Background Color.
		/// </summary>
		[DatabaseField]
		public string BackgroundColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BackgroundColor"), @"");
			}
			set
			{
				SetValue("BackgroundColor", value);
			}
		}


		/// <summary>
		/// Text Color.
		/// </summary>
		[DatabaseField]
		public string TextColor
		{
			get
			{
				return ValidationHelper.GetString(GetValue("TextColor"), @"");
			}
			set
			{
				SetValue("TextColor", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CustomTable_SectionColorThemesItem fields.
		/// </summary>
		[RegisterProperty]
		public CustomTable_SectionColorThemesItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CustomTable_SectionColorThemesItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CustomTable_SectionColorThemesItemFields : AbstractHierarchicalObject<CustomTable_SectionColorThemesItemFields>
		{
			/// <summary>
			/// The content item of type CustomTable_SectionColorThemesItem that is a target of the extended API.
			/// </summary>
			private readonly CustomTable_SectionColorThemesItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CustomTable_SectionColorThemesItemFields" /> class with the specified content item of type CustomTable_SectionColorThemesItem.
			/// </summary>
			/// <param name="instance">The content item of type CustomTable_SectionColorThemesItem that is a target of the extended API.</param>
			public CustomTable_SectionColorThemesItemFields(CustomTable_SectionColorThemesItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Name.
			/// </summary>
			public string Name
			{
				get
				{
					return mInstance.Name;
				}
				set
				{
					mInstance.Name = value;
				}
			}


			/// <summary>
			/// Css Class.
			/// </summary>
			public string CssClass
			{
				get
				{
					return mInstance.CssClass;
				}
				set
				{
					mInstance.CssClass = value;
				}
			}


			/// <summary>
			/// Background Color.
			/// </summary>
			public string BackgroundColor
			{
				get
				{
					return mInstance.BackgroundColor;
				}
				set
				{
					mInstance.BackgroundColor = value;
				}
			}


			/// <summary>
			/// Text Color.
			/// </summary>
			public string TextColor
			{
				get
				{
					return mInstance.TextColor;
				}
				set
				{
					mInstance.TextColor = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CustomTable_SectionColorThemesItem" /> class.
		/// </summary>
		public CustomTable_SectionColorThemesItem() : base(CLASS_NAME)
		{
			mFields = new CustomTable_SectionColorThemesItemFields(this);
		}

		#endregion
	}
}