//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using Njh.Kernel.Kentico.Models.CustomTables;

[assembly: RegisterCustomTable(CustomTable_ProfessionalTitleItem.CLASS_NAME, typeof(CustomTable_ProfessionalTitleItem))]

namespace Njh.Kernel.Kentico.Models.CustomTables
{
	/// <summary>
	/// Represents a content item of type CustomTable_ProfessionalTitleItem.
	/// </summary>
	public partial class CustomTable_ProfessionalTitleItem : CustomTableItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Njh.CustomTable_ProfessionalTitle";


		/// <summary>
		/// The instance of the class that provides extended API for working with CustomTable_ProfessionalTitleItem fields.
		/// </summary>
		private readonly CustomTable_ProfessionalTitleItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CustomTable_ProfessionalTitleItem fields.
		/// </summary>
		[RegisterProperty]
		public CustomTable_ProfessionalTitleItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CustomTable_ProfessionalTitleItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CustomTable_ProfessionalTitleItemFields : AbstractHierarchicalObject<CustomTable_ProfessionalTitleItemFields>
		{
			/// <summary>
			/// The content item of type CustomTable_ProfessionalTitleItem that is a target of the extended API.
			/// </summary>
			private readonly CustomTable_ProfessionalTitleItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CustomTable_ProfessionalTitleItemFields" /> class with the specified content item of type CustomTable_ProfessionalTitleItem.
			/// </summary>
			/// <param name="instance">The content item of type CustomTable_ProfessionalTitleItem that is a target of the extended API.</param>
			public CustomTable_ProfessionalTitleItemFields(CustomTable_ProfessionalTitleItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CustomTable_ProfessionalTitleItem" /> class.
		/// </summary>
		public CustomTable_ProfessionalTitleItem() : base(CLASS_NAME)
		{
			mFields = new CustomTable_ProfessionalTitleItemFields(this);
		}

		#endregion
	}
}