//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.CustomTables;
using Njh.Kernel.Kentico.Models.CustomTables;

[assembly: RegisterCustomTable(CustomTable_SearchQuickLinksItem.CLASS_NAME, typeof(CustomTable_SearchQuickLinksItem))]

namespace Njh.Kernel.Kentico.Models.CustomTables
{
    /// <summary>
    /// Represents a content item of type CustomTable_SearchQuickLinksItem.
    /// </summary>
    public partial class CustomTable_SearchQuickLinksItem : CustomTableItem
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "Njh.CustomTable_SearchQuickLinks";


        /// <summary>
        /// The instance of the class that provides extended API for working with CustomTable_SearchQuickLinksItem fields.
        /// </summary>
        private readonly CustomTable_SearchQuickLinksItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// Display Text.
        /// </summary>
        [DatabaseField]
        public string DisplayText
        {
            get
            {
                return ValidationHelper.GetString(GetValue("DisplayText"), @"");
            }
            set
            {
                SetValue("DisplayText", value);
            }
        }


        /// <summary>
        /// Url.
        /// </summary>
        [DatabaseField]
        public string Url
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Url"), @"");
            }
            set
            {
                SetValue("Url", value);
            }
        }


        /// <summary>
        /// Enabled.
        /// </summary>
        [DatabaseField]
        public bool Enabled
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Enabled"), true);
            }
            set
            {
                SetValue("Enabled", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with CustomTable_SearchQuickLinksItem fields.
        /// </summary>
        [RegisterProperty]
        public CustomTable_SearchQuickLinksItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with CustomTable_SearchQuickLinksItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class CustomTable_SearchQuickLinksItemFields : AbstractHierarchicalObject<CustomTable_SearchQuickLinksItemFields>
        {
            /// <summary>
            /// The content item of type CustomTable_SearchQuickLinksItem that is a target of the extended API.
            /// </summary>
            private readonly CustomTable_SearchQuickLinksItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="CustomTable_SearchQuickLinksItemFields" /> class with the specified content item of type CustomTable_SearchQuickLinksItem.
            /// </summary>
            /// <param name="instance">The content item of type CustomTable_SearchQuickLinksItem that is a target of the extended API.</param>
            public CustomTable_SearchQuickLinksItemFields(CustomTable_SearchQuickLinksItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// Display Text.
            /// </summary>
            public string DisplayText
            {
                get
                {
                    return mInstance.DisplayText;
                }
                set
                {
                    mInstance.DisplayText = value;
                }
            }


            /// <summary>
            /// Url.
            /// </summary>
            public string Url
            {
                get
                {
                    return mInstance.Url;
                }
                set
                {
                    mInstance.Url = value;
                }
            }


            /// <summary>
            /// Enabled.
            /// </summary>
            public bool Enabled
            {
                get
                {
                    return mInstance.Enabled;
                }
                set
                {
                    mInstance.Enabled = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="CustomTable_SearchQuickLinksItem" /> class.
        /// </summary>
        public CustomTable_SearchQuickLinksItem() : base(CLASS_NAME)
        {
            mFields = new CustomTable_SearchQuickLinksItemFields(this);
        }

        #endregion
    }
}